### ISSUE TITLE
Any benchmarks ?

### ISSUE THREAD

**Issue by eperry** [BigDataDevs/kafka-elasticsearch-consumer#51]
I am curious to why you would use this project over the Logstash Elasticsearch output?

I mean, I don't see any description or benchmarks to explain the benefit over Logstash. 

I am curious as I was thinking the same thing that I could write a simple Consumer to publish data to ES rather then use Logstash. Thinking it would perform better.  Since you have done all this work already (TYVM)  now I was hoping to find out more about what your experience and hopefully some benchmarks.

I am currently processing about 10K kafka messages a second, and expecting to be in the 50-100k range by the end of the year. I am currently running on 7 data nodes and expanding.

**Comment by mpopova-yottaa** [comment]
Hi, @eperry ,
Sorry for the log delay - August is a vacation month for most :)

So, why use this project (es-indexer) over Logstash? It really is a matter of taste and your intentions... : 

- Logstash is a very big generic project, with any "input" and any "output" you can think of :) - it makes it very big and not possible to use as a dependency lib (embedded) in your own project if needed. This is how we use es-indexer, by the way - as a dependency lib... Because of that, we can do additional things as we process events from Kafka - such as lookup of additional meta data from Mongo.... the limit is your imagination :)
- on the other side - es-indexer is a very specific project, it only reads data from Kafka and only indexes into ES - so it is optimized for that
- es-indexer allows you to have much finer-grained control over how you handle exceptions - which ones you ignore completely, which ones cause retries, which ones are considered non-recoverable and cause the app to shutdown all threads gracefully
-- es-indexer also allows you to decide what you do with those events that failed processing for any reason - we log them into a separate file, failed_events.log - and, thus, they can be re-processed later easily
-- es-indexer works with offsets of kafka partitions directly (using low-level consumer, not the high-level one in Kafka 0.8), committing them explicitly, and this makes it possible to have a much finer control over which offsets you can re-start the indexer from - you can specify an explicit offset value. LogStash only allows you to restart from EARLIEST or LATEST offset (at least AFAIK)

So, in summary, it is all about how much control you want to have over the processing.

I'm sure all this can be done with LogStash too - but it seemed easier for us to do it in a smaller more focused project. 

As to benchmarks: we have not created/ran some generic benchmarks, neither ran any comparison with Logstash. However, we do process 10K/sec events easily now with a 3-node ES cluster, and usually the bottleneck is in ES cluster load, not in the es-indexer. You start running into rejections from ES cluster due to its overload before you exhaust the es-indexer capacity. And if you do - you can simply start more indexers, as they are joining the same kafka consumer group and can scale out horizontally that way (provided you have enough partitions to share the load)

One thing we did to lessen the problem of overloaded ES cluster is by throttling the indexer when we start getting such ES exceptions. So, the indexer starts sleeping a bit between retries, and catches up with the backlog of data in Kafka as ES load improves.

Hope this helps,
Marina

**Comment by eperry** [comment]
Interesting thoughts, about the the single focus nature of the app.   I did experience lots of tuning issues of logstash, don't know if it was me or lack of documentation on how to tune it for performance.

Well I do need something that can consume at a fast rate, I am at 4K messages a second and I expect that to quadruple as we hit peak season so it is good to hear your getting 10k on a 3 node cluster as I have a ~10 node cluster and ELK seems still idle 

I like the idea of embedding it in an application for data enrichment or even "transformation" , I'll have to pass that idea on to the application teams

well once I rebuild my Kafka cluster one more time on newish hardware sometime this month, I'll put it though some tests and let you know.  


Thanks, this was not exactly what I was hoping for but it gave me LOTS of idea's to chew on and does answer the idea of what I was asking
