### ISSUE TITLE
when I run 2 consumers with the same topic and same consumerGroupName , the message was indexed 2 times

### ISSUE THREAD

**Issue by 87260280** [BigDataDevs/kafka-elasticsearch-consumer#53]
when i set the consumerGroupName to group-sp and with a topic has 5 partitions, i hava not just  got only one group-sp but group-sp_{0,1,2,3,4}, so why can't i consumer director with my zookeeper meta info?
ps:  my kafka version is 0.10
thanks @ppine7  !

**Comment by ppine7** [comment]
Hi, @87260280 ,
I'm not sure I understand your question.... But in case you are asking why there is a distinct group name for each partition's consumer - it is because we are using low-level consumer API for now (kafka0.8) - and each partion gets an individual consumer with the name constructed as <group_name from properties> + "_" + <partition_number>.

We do not yet support new consumers introduced in kafka 0.9 - it is work in progress.

thanks

**Comment by ppine7** [comment]
kafka 0.10 is now supported - hopefully this addresses your isuue
